extends Control

## Newspaper-style run ending display. Reads the RunSummary generated by
## GameManager; never reads live RunState (PRD 04 §11-§12).


func _ready() -> void:
	%RestartButton.pressed.connect(_on_restart_pressed)
	%MainMenuButton.pressed.connect(_on_main_menu_pressed)
	_populate()


func _populate() -> void:
	var summary: RunSummary = GameManager.get_last_summary()
	if summary == null:
		%EndingTitleLabel.text = "NO RUN DATA"
		%EndingDescriptionLabel.text = "This screen was opened without a finished run (debug navigation)."
		%DateLabel.text = "Day ? of the Glorious Reign"
		%FinalStatsLabel.text = ""
		%LawsCountLabel.text = ""
		%EndingsUnlockedLabel.text = ""
		%LegacySummaryLabel.text = ""
		return

	var ending: Dictionary = GameManager.get_content().get_ending(summary.ending_id)
	%MastheadLabel.text = str(ending.get("newspaper_masthead", "THE MINISTAN TIMES"))
	%DateLabel.text = "Day %d of the Glorious Reign" % summary.final_day
	%EndingTitleLabel.text = summary.ending_title.to_upper()
	%EndingIconLabel.text = str(ending.get("placeholder_icon", "📰"))
	%EndingDescriptionLabel.text = summary.ending_description
	%FinalStatsLabel.text = "💰 %d   🙂 %d   🛡 %d   👑 %d" % [
		int(summary.final_resources.get("treasury", 0)),
		int(summary.final_resources.get("happiness", 0)),
		int(summary.final_resources.get("order", 0)),
		int(summary.final_resources.get("elite_loyalty", 0)),
	]
	%LawsCountLabel.text = "Active laws: %d" % summary.active_laws.size()
	%EndingsUnlockedLabel.text = "Endings discovered: %d of %d" % [
		SaveManager.get_unlocked_endings().size(),
		GameManager.get_content().get_raw_endings().size(),
	]
	%LegacySummaryLabel.text = summary.legacy_text


func _on_restart_pressed() -> void:
	GameManager.restart_run()


func _on_main_menu_pressed() -> void:
	GameManager.return_to_main_menu()
