extends Control

## Newspaper-style run ending display. Reads the RunSummary generated by
## GameManager; never reads live RunState (PRD 04 §11-§12).


func _ready() -> void:
	%RestartButton.pressed.connect(_on_restart_pressed)
	%MainMenuButton.pressed.connect(_on_main_menu_pressed)
	_populate()


func _populate() -> void:
	var summary: RunSummary = GameManager.get_last_summary()
	if summary == null:
		%EndingTitleLabel.text = "NO RUN DATA"
		%EndingDescriptionLabel.text = "This screen was opened without a finished run (debug navigation)."
		%DateLabel.text = "Day ? of the Glorious Reign"
		%FinalStatsLabel.text = ""
		%LawsCountLabel.text = ""
		%EndingsUnlockedLabel.text = ""
		%RulerIdentityLabel.text = ""
		%RulerIdentityLabel.visible = false
		%NewEndingBadgeLabel.text = ""
		%NewEndingBadgeLabel.visible = false
		%RewardSummaryLabel.text = ""
		%LegacySummaryLabel.text = ""
		return

	var ending: Dictionary = GameManager.get_content().get_ending(summary.ending_id)
	%MastheadLabel.text = str(ending.get("newspaper_masthead", "THE MINISTAN TIMES"))
	%DateLabel.text = "Day %d of the Glorious Reign" % summary.final_day
	%EndingTitleLabel.text = summary.ending_title.to_upper()
	%EndingIconLabel.text = str(ending.get("placeholder_icon", "📰"))
	%EndingDescriptionLabel.text = summary.ending_description
	%FinalStatsLabel.text = "💰 %d   🙂 %d   🛡 %d   👑 %d" % [
		int(summary.final_resources.get("treasury", 0)),
		int(summary.final_resources.get("happiness", 0)),
		int(summary.final_resources.get("order", 0)),
		int(summary.final_resources.get("elite_loyalty", 0)),
	]
	%LawsCountLabel.text = "Active laws: %d" % summary.active_laws.size()
	%EndingsUnlockedLabel.text = "Endings discovered: %d of %d" % [
		MetaProgressionManager.get_unlocked_ending_ids().size(),
		GameManager.get_content().get_raw_endings().size(),
	]
	if summary.ruler_identity_title.is_empty():
		%RulerIdentityLabel.text = ""
		%RulerIdentityLabel.visible = false
	else:
		%RulerIdentityLabel.text = "Ruler identity: %s" % summary.ruler_identity_title
		%RulerIdentityLabel.visible = true

	if summary.is_new_ending:
		%NewEndingBadgeLabel.text = "NEW ENDING UNLOCKED"
		%NewEndingBadgeLabel.visible = true
	else:
		%NewEndingBadgeLabel.text = ""
		%NewEndingBadgeLabel.visible = false

	%RewardSummaryLabel.text = _format_reward_summary(summary)
	var legacy_text: String = summary.legacy_text
	if MetaProgressionManager.get_total_runs_completed() <= 1:
		legacy_text += "\n\nTry another run — endings and advisor stories change with your choices."
	%LegacySummaryLabel.text = legacy_text


func _format_reward_summary(summary: RunSummary) -> String:
	var lines: PackedStringArray = []
	lines.append("Medals earned: +%d" % summary.medals_earned)
	var breakdown: Dictionary = summary.reward_breakdown
	if breakdown.has("base"):
		lines.append("  Days survived: +%d" % int(breakdown.get("base", 0)))
	if int(breakdown.get("new_ending", 0)) > 0:
		lines.append("  New ending: +%d" % int(breakdown.get("new_ending", 0)))
	if int(breakdown.get("major_arcs", 0)) > 0:
		for arc_bonus in summary.completed_arc_bonuses:
			if str(arc_bonus.get("importance", "")) == "major":
				lines.append("  Major arc: +%d (%s)" % [
					int(arc_bonus.get("bonus", 0)), str(arc_bonus.get("display_name", "")),
				])
	if int(breakdown.get("minor_arcs", 0)) > 0:
		for arc_bonus in summary.completed_arc_bonuses:
			if str(arc_bonus.get("importance", "")) == "minor":
				lines.append("  Minor arc: +%d (%s)" % [
					int(arc_bonus.get("bonus", 0)), str(arc_bonus.get("display_name", "")),
				])
	lines.append("Total Medals: %d" % summary.medals_total_after)
	return "\n".join(lines)


func _on_restart_pressed() -> void:
	GameManager.restart_run()


func _on_main_menu_pressed() -> void:
	GameManager.return_to_main_menu()
